### ISSUE TITLE
Making Navbar fixed at top that is sticky Navbar

### ISSUE THREAD

**Issue by SUSHANT731** [HackClubRAIT/HackClubRAIT-Website.github.io#1]
Navbar will remain at top of the website while scrolling.Can I work on this issue ?

**Comment by Akshadaworlikar** [comment]
please assign this issue to me.

**Comment by SayantaniDeb** [comment]
can you assign this task to me?

**Comment by Chaitalishetty** [comment]
@SUSHANT731 yeah sure. Assigning this issue to you . Happy coding!
