### ISSUE TITLE
Hover effects on icons in team section

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#106]
![image](https://user-images.githubusercontent.com/66556168/151346415-100474ac-b45b-4c25-a92d-87d21e13477d.png)

**Comment by Soham56** [comment]
Hey ! can I contribute on this issue ?

**Comment by Soham56** [comment]
can you once confirm, that if I get the opportunity to contribute, then I have to create hover effects on those classes write?

<img width="553" alt="Screenshot 2022-01-27 230328" src="https://user-images.githubusercontent.com/74524863/151412602-21059c15-efd7-4437-9bb1-3c7a0a1f2ec1.png">

**Comment by Chaitalishetty** [comment]
Hey @Soham56 Wait till 1st jan , after that I will surely assign the issue to you.

**Comment by Soham56** [comment]
Thank you so much @Chaitalishetty, I guess you want to say 1st February write?

Ok, no problem.

**Comment by Srijita-Mandal** [comment]
I can contribute on that issue

**Comment by Chaitalishetty** [comment]
> Thank you so much @Chaitalishetty, I guess you want to say 1st February write?
> 
> Ok, no problem.

Oh sorry 😂 , 1st Feb.

**Comment by Soham56** [comment]
It's ok 😊

**Comment by rohit-raj25** [comment]
I also wanna contribute to this issue

**Comment by Chaitalishetty** [comment]
Do check the readme section.

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by ShrutiKapure** [comment]
I want to work on this issue under **JWOC**.

**Comment by combatantash** [comment]
I want to work on this issue under JWOC

**Comment by PrajwalDhule** [comment]
hello, I would like to work on this issue

**Comment by Chaitalishetty** [comment]
@Arun5023 Assigning this issue to you . Happy Coding !

**Comment by Sanghu01** [comment]
I want to contribute in this issue .

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
