### ISSUE TITLE
Remove scrollbar in mobile view

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#107]

**Comment by varunwho** [comment]
Hey @Chaitalishetty can I work on this?

**Comment by Devmindtk** [comment]
I would like to work on this issue @Chaitalishetty  please assign it to me.

**Comment by mnnkhndlwl** [comment]
I also wanna contribute to this issue

**Comment by Chaitalishetty** [comment]
Do check the readme section.

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by mnnkhndlwl** [comment]
I want to work on this issue under JWOC

**Comment by ZaidMujahid** [comment]
I want to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@mnnkhndlwl Assigning this issue to you . Happy Coding !

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by Sanghu01** [comment]
In what time to submit and how. plz tell me
