### ISSUE TITLE
Click on social media icon in Contact us page link fails to open in new tab

### ISSUE THREAD

**Issue by Yasshu55** [HackClubRAIT/HackClubRAIT-Website.github.io#110]
When we click on the Social media icon on the contact page it doesn't redirect to the new tab instead it loads in the current tab, whereas on the home page it redirects, Hope to fix this issue please assign it to me

**Comment by Mohith234** [comment]
I want to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@Yasshu55 Won't you be needing everyone's social media for that?

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by Dhyey17** [comment]
I want to work on this issue under JWOC
