### ISSUE TITLE
Improve the cards UI in the teams section and make it responsive too

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#125]

**Comment by sayan404** [comment]
I want to work in this issue under JWOC.

**Comment by Chaitalishetty** [comment]
@sayan404 Assigning you this issue . Happy Coding !

**Comment by AtriSukul1508** [comment]
I would like to work on this issue under JWOC

**Comment by Atif0604** [comment]
I would like to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I would like to work on this issue under JWOC
