### ISSUE TITLE
Enhance the inputs in the contact us page

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#131]
Improve the UI of inputs

**Comment by SantanuShaw** [comment]
I want to contribute under jwoc

**Comment by Chaitalishetty** [comment]
@SantanuShaw Assigning you this issue. Happy Coding!

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by Chaitalishetty** [comment]
@whiteHatpro Assigning you this issue. Happy Coding!!

**Comment by whiteHatpro** [comment]
@Chaitalishetty i have done the changes for the inputs page
kindly review it!!

**Comment by whiteHatpro** [comment]
@Chaitalishetty please review it!!
