### ISSUE TITLE
Remove the underline 

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#132]
In home page, there is an underline on hover. 
![image](https://user-images.githubusercontent.com/66556168/153616549-a7a4fa29-7fb3-4222-a121-daaa01b2dd36.png)

**Comment by sayan404** [comment]
I want work in this issue under JWOC.

**Comment by Chaitalishetty** [comment]
@sayan404 Assigning you this issue. Happy Coding !

**Comment by sayan404** [comment]
I want to work on this issue under JWOC.

**Comment by Chaitalishetty** [comment]
@sayan404 Assigning you this issue. Happy Coding!
