### ISSUE TITLE
Make the image in opprortunities tab responsive

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#139]
![image](https://user-images.githubusercontent.com/66556168/153742031-30130293-ced4-4d26-850a-57be12445480.png)

**Comment by sayan404** [comment]
I want to work on this issue under JWOC.

**Comment by Chaitalishetty** [comment]
@sayan404 Assigning you this issue . Happy Coding !
