### ISSUE TITLE
Add discord icon in footer contacts

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#140]
![image](https://user-images.githubusercontent.com/66556168/153742336-585545aa-db7d-49c6-b84b-7ded1cfbf637.png)
Add discord icon here

**Comment by AtriSukul1508** [comment]
I would like to contribute to this issue under JWOC

**Comment by Chaitalishetty** [comment]
@AtriSukul1508 Assigning you this issue. Happy Coding !

**Comment by riiyaaa** [comment]
I would like to work on it under JWOC.
