### ISSUE TITLE
Improve the UI of the contributors page

### ISSUE THREAD

**Issue by AtriSukul1508** [HackClubRAIT/HackClubRAIT-Website.github.io#141]
**Is your feature request related to a problem? Please describe.**
Yes ,want to improve the UI of the contributors page

**Describe the solution you'd like**
Will improve the cards UI and the overall UI of the page
**Describe alternatives you've considered**

**Additional context**

### Are you participating under any open-source program? ### 
JWOC

**Comment by AtriSukul1508** [comment]
I would like to contribute to this issue under JWOC

**Comment by Chaitalishetty** [comment]
@AtriSukul1508 Assigning this issue to you . Happy Coding!
