### ISSUE TITLE
Image overflow in the 2nd section and 3rd section of home page in mobile view

### ISSUE THREAD

**Issue by Aniket-508** [HackClubRAIT/HackClubRAIT-Website.github.io#145]
![Screenshot (353)](https://user-images.githubusercontent.com/71957423/153812358-68421dec-9e7a-45e2-8f5c-7da76e898482.png)

**Comment by Aniket-508** [comment]
@Chaitalishetty I want to work on this issue under JWoC.

**Comment by Chaitalishetty** [comment]
@Aniket-508 Assigning you this issue. Happy Coding!
