### ISSUE TITLE
How to join the `HackClubRAIT` organization?

### ISSUE THREAD

**Issue by iatharva** [HackClubRAIT/HackClubRAIT-Website.github.io#15]
**Describe the bug**
I know this is not the correct place to submit/ ask this, but there are no instructions on how one can join the organization.
I tried to reach out to people from org who are visible but they haven't mention any email id to contact and there are no options on Instagram and LinkedIn to message directly as the profiles are private.

Do guide me on how can I join the org?

**To Reproduce**
None

**Expected behaviour**
There should be a repository where people can open issues to join the organization.

**Comment by siddhi-244** [comment]
> **Describe the bug** I know this is not the correct place to submit/ ask this, but there are no instructions on how one can join the organization. I tried to reach out to people from org who are visible but they haven't mention any email id to contact and there are no options on Instagram and LinkedIn to message directly as the profiles are private.
> 
> Do guide me on how can I join the org?
> 
> **To Reproduce** None
> 
> **Expected behaviour** There should be a repository where people can open issues to join the organization.

Actually this is a club and we run some interviews to select our members.

**Comment by Chaitalishetty** [comment]
@iatharva  This is an open source club started in rait college and we will soon be putting link to the socials of a the core team on our website

**Comment by iatharva** [comment]
Okay, sure.

**Comment by iatharva** [comment]
> > **Describe the bug** I know this is not the correct place to submit/ ask this, but there are no instructions on how one can join the organization. I tried to reach out to people from org who are visible but they haven't mention any email id to contact and there are no options on Instagram and LinkedIn to message directly as the profiles are private.
> > Do guide me on how can I join the org?
> > **To Reproduce** None
> > **Expected behaviour** There should be a repository where people can open issues to join the organization.
> 
> Actually this is a club and we run some interviews to select our members.

So what is the next step for me?
