### ISSUE TITLE
The "<" in the <hackclub/> logo of Opportunity section  is missing

### ISSUE THREAD

**Issue by sayan404** [HackClubRAIT/HackClubRAIT-Website.github.io#150]
**Describe the bug**
The "<" in the <hackclubrait/> logo of Opportunity section  is missing.

**Expected behavior**
It should show the logo <HackClub/> in the nav bar of Opportunity section.
**Screenshots**
 ##
![Screenshot 2022-02-14 152805](https://user-images.githubusercontent.com/95490367/153844588-e8808bc1-9f67-4818-8490-c7f3cae702ad.jpg)

**Additional context**

### Are you participating under any open-source program? ### 
Yes . The name of the program is JWOC.

**Comment by sayan404** [comment]
I want work in this issue under JWOC.

**Comment by Chaitalishetty** [comment]
@sayan404 Assigning you this issue. Happy Coding !!
