### ISSUE TITLE
Smooth scrolling 

### ISSUE THREAD

**Issue by pranavsuriya-sr** [HackClubRAIT/HackClubRAIT-Website.github.io#153]
**Is your feature request related to a problem? Please describe.**
Adding a smooth scrolling feature to the navigate to top button will ensure smooth transition of the page.

**Comment by pranavsuriya-sr** [comment]
I want to work on this issue under JWOC

**Comment by Chaitalishetty** [comment]
@pranavsuriya-sr Assigning you this issue. Happy Coding !
