### ISSUE TITLE
Add SearchBar in the contributors page

### ISSUE THREAD

**Issue by AtriSukul1508** [HackClubRAIT/HackClubRAIT-Website.github.io#156]
**Is your feature request related to a problem? Please describe.**
Add a searchbar in the contributors page

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Are you participating under any open-source program? ### 
( fill NA if none )

**Comment by codervivek5** [comment]
I want to work on it

**Comment by Chaitalishetty** [comment]
@AtriSukul1508 Assigning you this issue . Happy coding !
