### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by ZaidKhan2002** [HackClubRAIT/HackClubRAIT-Website.github.io#16]
**Describe the bug**
In README.md navigation to project directory is incorrect as the name of directory should not be HackClubRAIT-Website

**Comment by ZaidKhan2002** [comment]
Can I solve that issue ?

**Comment by Chaitalishetty** [comment]
@ZaidKhan2002 you have already been assigned an issue . So solve that and then will assign this issue to you!

**Comment by ZaidKhan2002** [comment]
Created PR for that issue you can review that

**Comment by AnirudhEyyani** [comment]
Can I solve that issue ?

**Comment by copyNinja1219** [comment]
can I solve this issue ?

**Comment by Chaitalishetty** [comment]
@ZaidKhan2002 Assgning this issue to you. Happy Coding !
