### ISSUE TITLE
Updating the heading of the readme file.

### ISSUE THREAD

**Issue by gullapalli9482** [HackClubRAIT/HackClubRAIT-Website.github.io#160]
The heading of the readme file contains "This is the official website of the HackClubRAIT website". Providing the link of the website(through hyperlinking) would improve the readability of the readme file instead of searching for the website link. Or changing the heading would give a good impression for first-timers.

**Comment by gullapalli9482** [comment]
I would like to work on this issue , do assign me

**Comment by Chaitalishetty** [comment]
@gullapalli9482 Assigning you this issue. Happy Coding!

**Comment by YashAryanTheCoder** [comment]
## I would like to work on this issue , do assign me

**Comment by sayan404** [comment]
If this issue is unsolved , I would like to work in this issue under JWOC .
