### ISSUE TITLE
Project page fixing button placement, enhancing design and making it responsive

### ISSUE THREAD

**Issue by sn2606** [HackClubRAIT/HackClubRAIT-Website.github.io#18]
For project cards, the button placement is wrong and styling could be improved.
[Page Link ](https://hackclubrait.github.io/HackClubRAIT-Website.github.io/projects.html)

<img width="960" alt="01 10 2021_16 46 45_REC" src="https://user-images.githubusercontent.com/58822437/135612073-9c01a2ab-62f8-4140-a72b-390b86eb550c.png">

<img width="258" alt="01 10 2021_16 47 48_REC" src="https://user-images.githubusercontent.com/58822437/135612096-aea9bcd3-9acb-4839-b2f3-96538388956f.png">

I would like to work on this issue. Please assign this to me.

**Comment by Chaitalishetty** [comment]
@sn2606 Assigning this issue to you. Happy Coding !
