### ISSUE TITLE
Make home page banner centered and favicon addition

### ISSUE THREAD

**Issue by developer-diganta** [HackClubRAIT/HackClubRAIT-Website.github.io#20]
![image](https://user-images.githubusercontent.com/65999534/135617566-513ef3a1-44c7-450c-acdc-9ae765ea6cfc.png)
The banner would look better if it covered the entire visible viewport on opening the home page. Also the banner would look better if centered. And favicon is missing. I would like to work on these issues.

**Comment by Chaitalishetty** [comment]
@developer-diganta Assigning this issue to you. Happy Coding !
