### ISSUE TITLE
Homepage-Responsive-Hamburger menu

### ISSUE THREAD

**Issue by SayantaniDeb** [HackClubRAIT/HackClubRAIT-Website.github.io#21]
**Is your feature request related to a problem? Please describe.**
The homepage is not responsive

**Describe the solution you'd like**
The homepage will be made responsive with hamburger menu for navbar

**Comment by SayantaniDeb** [comment]
Please assign this task to me.

**Comment by Chaitalishetty** [comment]
This issue is already been assigned here #2.
