### ISSUE TITLE
Aligning tags in projects page and styling cards

### ISSUE THREAD

**Issue by ShyamSunder149** [HackClubRAIT/HackClubRAIT-Website.github.io#24]
**Is your feature request related to a problem? Please describe.**
The tags mentioned in the cards in projects are not aligned properly

**Describe the solution you'd like**
I would like to align tags properly and style the project cards a little bit

**Describe alternatives you've considered**
the alternative would be removal of tags or keeping tags as bulletin points

### Are you participating under any open-source program? ### 
Yes, Hacktoberfest

**Comment by Chaitalishetty** [comment]
@ShyamSunder149 Assigning this issue to you. Happy Coding !
