### ISSUE TITLE
footer is not responsive can i work on it

### ISSUE THREAD

**Issue by arunsingh009** [HackClubRAIT/HackClubRAIT-Website.github.io#29]
**Describe the bug**

**Expected behavior**
A clear and concise description of what you expected to happen
![bug1](https://user-images.githubusercontent.com/66819980/135665491-3028e72c-9d08-4e63-8989-a60512722c84.png)
.

**Screenshots**

**Additional context**

### Are you participating under any open-source program? ### 
( fill NA if none )

**Comment by Chaitalishetty** [comment]
@arunsingh009 Assigning this issue to you. Happy Coding !

**Comment by arunsingh009** [comment]
Thanks For this i am glad this will be my first contribution in world of open source
