### ISSUE TITLE
Responsive sections

### ISSUE THREAD

**Issue by hdck007** [HackClubRAIT/HackClubRAIT-Website.github.io#3]
#### Before Change
![image](https://user-images.githubusercontent.com/68905333/135564187-c4ceb112-f010-49e0-a1c9-efadd1f83027.png)

#### After change
![image](https://user-images.githubusercontent.com/68905333/135564105-63cf1882-7933-48e1-99e6-48864b00e930.png)

**Comment by Akshadaworlikar** [comment]
please assign this issue to me

**Comment by Chaitalishetty** [comment]
@hdck007 Assigning this issue to you. Happy coding !

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
