### ISSUE TITLE
I would like to add hover effects to the navbar.

### ISSUE THREAD

**Issue by siddhi-244** [HackClubRAIT/HackClubRAIT-Website.github.io#33]
**Is your feature request related to a problem? Please describe.**
I think hover effects make a website look pretty.

### Are you participating under any open-source program? ### 
Hacktoberfest 
( fill NA if none )

**Comment by siddhi-244** [comment]
Plzz assign this to me under Hacktoberfest

**Comment by Chaitalishetty** [comment]
@siddhi-244 Assigning this issue to you . Happy Coding !
