### ISSUE TITLE
Contact Us page responsiveness

### ISSUE THREAD

**Issue by ri-tae-ka** [HackClubRAIT/HackClubRAIT-Website.github.io#37]
The contact us page is not responsive, i'd like to work on it under hacktoberfest.

**Comment by Chaitalishetty** [comment]
@ri-tae-ka Assigning this issue to you . Happy Coding !

**Comment by ri-tae-ka** [comment]
> @ri-tae-ka Assigning this issue to you . Happy Coding !

The issue has already been fixed!
I'll close this request
