### ISSUE TITLE
Spacing the sections to full screen, i.e, about hackclub, hackclub rait, vision.

### ISSUE THREAD

**Issue by HardikSJain** [HackClubRAIT/HackClubRAIT-Website.github.io#42]
**Is your feature request related to a problem? Please describe.**
It would look great if the sections are of the resolution of full screen, after making it full screen we'll need to make the text centralized. Also a slight transition delay of 500ms in the hover effect of navigation bar would look beautiful. One more change I can suggest is that on the home page "HackClub RAIT Initiative for students by students" can come with a transition of fade down, it'd look beautiful. Also on the title bar of home screen it is written "Home", it'd be better if we change it to "HackClub RAIT"

### Are you participating under any open-source program? ### 
Yes, Hacktober Fest.

**Comment by Chaitalishetty** [comment]
@HardikSJain Assigning this issue to you. Happy coding!
