### ISSUE TITLE
Linking websites on home page and logo redirecting to home

### ISSUE THREAD

**Issue by kshitija-2001** [HackClubRAIT/HackClubRAIT-Website.github.io#45]
**Describe the bug**
Home page links not redirecting properly and logo not redirecting to home

**Expected behavior**
links to be updated and clicking on logo it should redirect to home page

**Screenshots**
![image](https://user-images.githubusercontent.com/60540365/135740879-c45ab3e8-f1f5-4a8e-9088-32dab4054abe.png)

**Additional context**

### Are you participating under any open-source program? ### 
Hacktoberfest

**Comment by Amritanshu02** [comment]
Hello, I would like to work upon this issue, could you assign it to me

**Comment by ZaidKhan2002** [comment]
I opened this issue yesterday #40

**Comment by Chaitalishetty** [comment]
@kshitija-2001 The logo redirecting issue is already being raised here #40 but you can work on redirection of other links on homepage. Assigning this issue to you . Happy Coding !

**Comment by kshitija-2001** [comment]
Yes sure I will go ahead with linking other links

**Comment by chandresh1339** [comment]
I can work. please give me 1 chance.

**Comment by ZaidKhan2002** [comment]
@chandresh1339 you can look at issue #40 and ask @Chaitalishetty to assign you the task

**Comment by chandresh1339** [comment]
Sure. @Chaitalishetty kindly assign me the task.
