### ISSUE TITLE
home page banner responsiveness

### ISSUE THREAD

**Issue by shreyamedehal** [HackClubRAIT/HackClubRAIT-Website.github.io#47]
**Describe the bug**
making the home page banner responsive

**Screenshots**
![Home  (2)](https://user-images.githubusercontent.com/82696347/135743214-8d171426-5a23-410b-a41f-89a94f3c729c.png)

### Are you participating under any open-source program? ### 
hacktoberfest

**Comment by Chaitalishetty** [comment]
@shreyamedehal Assigning this issue to you. Happy Coding !
