### ISSUE TITLE
Make Team Section Responsive 

### ISSUE THREAD

**Issue by ZaidKhan2002** [HackClubRAIT/HackClubRAIT-Website.github.io#5]
<img width="425" alt="Screenshot 2021-10-01 at 10 24 47 AM" src="https://user-images.githubusercontent.com/71960989/135567374-8333f312-ede2-40bc-8bd9-bb281dcf2170.png">

**Comment by ZaidKhan2002** [comment]
I want to work on this issue

**Comment by Chaitalishetty** [comment]
@ZaidKhan2002 Assigning this issue to you. Happy Coding!
