### ISSUE TITLE
Hover Effect on contact us page for social links

### ISSUE THREAD

**Issue by ZaidKhan2002** [HackClubRAIT/HackClubRAIT-Website.github.io#54]
**Is your feature request related to a problem? Please describe.**
On Contact us page we should have hover effect just like we have it on our footer section of website.

**Describe the solution you'd like**
Hover Effect

**Comment by rishikeshreddyakkireddy** [comment]
can you assign this issue to me, I would like to work on this issue.

**Comment by ZaidKhan2002** [comment]
@rishikeshreddyakkireddy ask maintainer @Chaitalishetty
