### ISSUE TITLE
the logo at the nav bar can be inserted in an anchor tag 

### ISSUE THREAD

**Issue by HardikSJain** [HackClubRAIT/HackClubRAIT-Website.github.io#57]
**Is your feature request related to a problem? Please describe.**
the logo at the nav bar can be inserted in an anchor tag so that it can redirect to index.html from anywhere... This will be a helpful feature.

### Are you participating under any open-source program? ### 
hacktober

**Comment by Chaitalishetty** [comment]
@HardikSJain Assigning this issue to you . Happy Coding !

**Comment by HardikSJain** [comment]
@addisonhardley already added this feature in his/her pr and got merged to the main repo.
