### ISSUE TITLE
To add a new logo

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [HackClubRAIT/HackClubRAIT-Website.github.io#59]
I have made a new logo for HackCluvRAIT in which the Background is blurred please assign me so I can create a PR.
![hackclubrait-logo](https://user-images.githubusercontent.com/73253354/135970134-e118ce3c-7197-4d30-bd16-57f431a33534.png)

**Comment by Chaitalishetty** [comment]
@pruthvirajjadhav1 Assigning this issue to you . Happy Coding !
