### ISSUE TITLE
homepage background  fix and scrollbar colour change

### ISSUE THREAD

**Issue by SayantaniDeb** [HackClubRAIT/HackClubRAIT-Website.github.io#6]
please assign this task to me

**Comment by Akshadaworlikar** [comment]
please assign this task to me

**Comment by Chaitalishetty** [comment]
@SayantaniDeb Assigning this issue to you. Happy coding!

**Comment by TD-17** [comment]
Hi! I want to contribute to this repository. Could you please assign this issue to me?
