### ISSUE TITLE
wrap the text around the image 

### ISSUE THREAD

**Issue by shreyamedehal** [HackClubRAIT/HackClubRAIT-Website.github.io#60]
**Describe the bug**
Wrap the text around the image in the home page sections ("About HackClub" and "HackClub RAIT) in responsive view.

**Expected behavior**
Responsiveness and Enhanced UI 

**Screenshots**
![home section](https://user-images.githubusercontent.com/82696347/135979975-7e523c60-6cab-4e47-a778-b4b9992ad853.png)

### Are you participating under any open-source program? ### 
Hacktoberfest

**Comment by Chaitalishetty** [comment]
@shreyamedehal Assigning this issue to you . Happy Coding !

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
