### ISSUE TITLE
footer links are not looking good

### ISSUE THREAD

**Issue by arunsingh009** [HackClubRAIT/HackClubRAIT-Website.github.io#61]
**Describe the bug**
footer links is not looking good

**Expected behavior**
Footer link is not looking good specially contact us.
![image](https://user-images.githubusercontent.com/66819980/135987175-4aa2e94b-c911-41a6-9938-088913057175.png)
![image](https://user-images.githubusercontent.com/66819980/135987392-bc334f0d-cb1f-492f-9d34-9ad7ec9fc183.png)

**Screenshots**

**Additional context**

### Are you participating under any open-source program? ### 
( fill NA if none )

**Comment by arunsingh009** [comment]
if valid issue please assign this to me

**Comment by Chaitalishetty** [comment]
@arunsingh009 Assigning this issue to you. Happy Coding !
