### ISSUE TITLE
Content part not responsive

### ISSUE THREAD

**Issue by ZaidKhan2002** [HackClubRAIT/HackClubRAIT-Website.github.io#64]
**Describe the bug**
Content part in main page is not responsive in mobile size

**Expected behaviour**
Images should be on top and then text

**Screenshots**
<img width="965" alt="Screenshot 2021-10-05 at 5 33 00 PM" src="https://user-images.githubusercontent.com/71960989/136018987-5012f731-1c93-4ad9-b07f-c7d292f25488.png">

**Comment by Chaitalishetty** [comment]
@ZaidKhan2002 Assigning this issue to you .Happy Coding !
