### ISSUE TITLE
Bug in Contributers page

### ISSUE THREAD

**Issue by Chaitalishetty** [HackClubRAIT/HackClubRAIT-Website.github.io#67]
**Describe the bug**
In contributors page, the followers and following is not correct.

**Comment by Chaitalishetty** [comment]
@addisonhardley as you already contributed in the project is it okay with you if I assign this issue to @pratik1424 so he can make the necessary changes.

**Comment by pratik1424** [comment]
@addisonhardley true, scraping data from each of the contributor's account is taking too much time and making the page unresponsive. @Chaitalishetty what should we do, we can just keep contributions and followers or go with @addisonhardley 's solution.

**Comment by Chaitalishetty** [comment]
@pratik1424 you can keep only the number of contributions

**Comment by addisonhardley** [comment]
@pratik1424 Thanks :D.
@Chaitalishetty, Could you assign this issue to me? I'll create a PR after that.
