### ISSUE TITLE
Contact Form With Tilt Image Hover Effect

### ISSUE THREAD

**Issue by vijeta-2000** [HackClubRAIT/HackClubRAIT-Website.github.io#68]
**Describe the bug**
Improvement of ui design in contact form.

### Are you participating under any open-source program? ### 
Hackoctoberfest 2021

**Comment by Chaitalishetty** [comment]
@vijeta-2000 Assigning this issue to you. Happy Coding !

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC
